networks:
  my-network:
    driver: bridge

services:
  hexagonal-architecture-springboot-mongodb-co-work-booking-app:
    build: .
    container_name: "hexagonal-architecture-container"
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    networks:
      - my-network
    environment:
      - V_MONGODB_HOST=CoWorkBooking-mongodb
      - V_MONGODB_PORT=27017
      - V_MONGODB_URI=mongodb://CoWorkBooking-mongodb:27017/CoWorkBooking
      - V-JWT-SECRET-KEY=v2ZQhjIROzzMkAflVH/0k1RbqCuqeqZTxcczDkiQVEs=
      - V-EMAIL-FROM=example@hotmail.com
      - V-EMAIL-USERNAME=example@hotmail.com
      - V-EMAIL-PASSWORD=example
      - V-EMAIL-SMTP-HOST=smtp-mail.outlook.com

  mongodb:
    container_name: "CoWorkBooking-mongodb"
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - my-network

volumes:
  mongo-data: