FROM openjdk:17-oracle
WORKDIR /CoWorkBooking-Backend
COPY target/hexagonal-0.0.1-SNAPSHOT.jar hexagonal-architecture-springboot-mongodb-co-work-booking-app.jar
ENTRYPOINT ["java","-jar","hexagonal-architecture-springboot-mongodb-co-work-booking-app.jar"]

#FROM openjdk:17-oracle
#WORKDIR /CoWorkBooking-Backend
#COPY target/hexagonal-0.0.1-SNAPSHOT.jar hexagonal-architecture-springboot-mongodb-co-work-booking-app.jar
#EXPOSE 8080
#CMD ["java", "-jar", "hexagonal-architecture-springboot-mongodb-co-work-booking-app.jar"]
#
